const makro = [
  { item3: "OLEJ" },
  { item3: "OLIWA Z OLIWEK" },
  { item3: "SYROP KLONOWY" },
  { item3: "BARWNIK CIEMNY" },
  { item3: "WANILIA KONCENTRAT" },
  { item3: "MASLO KLAROWANE" },
  { item3: "GOFRY" },
  { item3: "LODY TRUSKAWKOWE" },
  { item3: "LODY WANILIOWE" },
  { item3: "LODY CZEKOLADOWE" },
  { item3: "KAKAO NATURALNE GORZKIE" },
  { item3: "SOS SOJOWY" },
  { item3: "PASZTET Z WATROBEK PATTIE" },
  { item3: "MIOD" },
  { item3: "MAKARON SPAGHETTI" },
  { item3: "MOZARELLA TWRDA BLOK" },
  { item3: "CAMEMBERT" },
  { item3: "TOFU" },
  { item3: "FRYTKI" },
  { item3: "DORSZ" },
  { item3: "PSTRAG" },
  { item3: "KREWETKI" },
  { item3: "WATROBKI DROBIOWE MROZONE" },
  { item3: "WOLOWINA KOSTKA" },
  { item3: "CZOSNEK OBRANY" },
  { item3: "KIELKI DO DEKORACJI" },
  { item3: "KETCHUP" },
  { item3: "MAJONEZ" },
  { item3: "SMIETANA 36%" },
  { item3: "NABOJE DO BITEJ SMIETANY" },
  { item3: "POJEMNIKI NA WYNOS DUZE" },
  { item3: "POJEMNIKI NA WYNOS MALE " },
];

export default makro;
