const polskaHurtownia = [
  { item2: "KOSTKA ROSOLOWA" },
  { item2: "KOSTKA MIESNA" },
  { item2: "KOSTKA WARZYWNA" },
  { item2: "KONCENTRAT POMIDOROWY" },
  { item2: "CUKIER PUDER" },
  { item2: "PROSZEK DO PIECZENIA" },
  { item2: "CUKIER WANILIOWY" },
  { item2: "SODA OCZYSZCZONA" },
  { item2: "KWASEK CYTRYNOWY " },
  { item2: "ZELATYNA" },
  { item2: "DROZDZE SUCHE" },
  { item2: "BUDYN WANILIOWY" },
  { item2: "ZUREK" },
  { item2: "MAGI" },
  { item2: "OCET 10%" },
  { item2: "OCET JABLKOWY" },
  { item2: "FASOLA JAS " },
  { item2: "BULKA TARTA" },
  { item2: " MAKA TORTOWA" },
  { item2: "MAKA PSZENNA NA CHLEB" },
  { item2: "MAKA ZIEMNIACZANA" },
  { item2: "OSCYPEK" },
  { item2: "CHRZAN TARTY" },
  { item2: "MUSZTARDA" },
  { item2: "PIETRUSZKA KORZEN" },
  { item2: "SELER KORZEN" },
  { item2: "BURAKI SWIEZE" },
  { item2: "TWAROG POLTLUSTY" },
  { item2: "SMALEC KOSTKA" },
  { item2: "SMALEC BATON TARCZYNSKI" },
  { item2: "MARGARYNA KOSTKA" },
];

export default polskaHurtownia;
