const vegetables = [
  { item: "ZIEMNIAKI CZERWONE - RED POTATOES" },
  { item: "CEBULA BIALA - WHITE ONNION" },
  { item: "KAPUSTA BIALA - WHITE CABBAGE" },
  { item: "KAPUSTA CZERWONA - RED CABBAGE" },
  { item: "KAPUSTA STORZKOWA - POINTED CABBAGE" },
  { item: "MARCHEW - CARROTS" },
  { item: "MLODA MARCHEWKA - NEW CARROTS" },
  { item: "PAPRYKA MIX - MIX PEPPERS" },
  { item: "PIECZARKI - MUSHROOMS" },
  { item: "PIETRUSZKA DEKORACYJNA - PARSLEY" },
  { item: "OGOREK SWIEZY - CUCUMBER" },
  { item: "CYTRYNY - LEMON" },
  { item: "LIMONKI - LIME" },
  { item: "JABLKA - APPLE" },
  { item: "POMIDORY DUZE - LARGE TOMATOES" },
  { item: "POMIDORKI KOKTAJLOWE - COCTAIL TOMATOES" },
  { item: "KALAFIOR DUZY - CAULIFLOWER" },
  { item: "SALATA MIX - MIX SALAD" },
  { item: "RUKOLA - ROCKET SALAD" },
  { item: "POR - LEEK" },
  { item: "MIETA - MINT" },
  { item: "KOPER - DILL " },
  { item: "SZCZYPIOR GRUBY - SPRING ONIONS" },
  { item: "ROZMARYN - RESEMARY" },
  { item: "TYMIANEK - THYME" },
  { item: "MASLO ZWYKLE - BUTTER " },
  { item: "ZURAWINA -CRAMBERY SAUCE" },
  { item: "JAJKA - EGG" },
  { item: "MLEKO - MILK" },
  { item: "KWASNA SMIETANA - SOUR CREAM" },
  { item: "SMIETANA 36% - WEEPING CREAM" },
];

export default vegetables;
