const makro = [
  { item: "OLEJ", count: 0 },
  { item: "OLIWA Z OLIWEK", count: 0 },
  { item: "SYROP KLONOWY", count: 0 },
  { item: "BARWNIK CIEMNY", count: 0 },
  { item: "WANILIA KONCENTRAT", count: 0 },
  { item: "MASLO KLAROWANE", count: 0 },
  { item: "GOFRY", count: 0 },
  { item: "LODY TRUSKAWKOWE", count: 0 },
  { item: "LODY WANILIOWE", count: 0 },
  { item: "LODY CZEKOLADOWE", count: 0 },
  { item: "KAKAO NATURALNE GORZKIE", count: 0 },
  { item: "SOS SOJOWY", count: 0 },
  { item: "PASZTET Z WATROBEK PATTIE", count: 0 },
  { item: "MIOD", count: 0 },
  { item: "MAKARON SPAGHETTI", count: 0 },
  { item: "MOZARELLA TWRDA BLOK", count: 0 },
  { item: "CAMEMBERT", count: 0 },
  { item: "TOFU", count: 0 },
  { item: "FRYTKI", count: 0 },
  { item: "DORSZ", count: 0 },
  { item: "PSTRAG", count: 0 },
  { item: "KREWETKI", count: 0 },
  { item: "WATROBKI DROBIOWE MROZONE", count: 0 },
  { item: "WOLOWINA KOSTKA", count: 0 },
  { item: "CZOSNEK OBRANY", count: 0 },
  { item: "KIELKI DO DEKORACJI", count: 0 },
  { item: "KETCHUP", count: 0 },
  { item: "MAJONEZ", count: 0 },
  { item: "SMIETANA 6%", count: 0 },
  { item: "NABOJE DO BITEJ SMIETANY", count: 0 },
  { item: "POJEMNIKI NA WYNOS DUZE", count: 0 },
  { item: "POJEMNIKI NA WYNOS MALE ", count: 0 },
];

export default makro;
