const polskaHurtownia = [
  { item: "KOSTKA ROSOLOWA", count: 0 },
  { item: "KOSTKA MIESNA", count: 0 },
  { item: "KOSTKA WARZYWNA", count: 0 },
  { item: "KONCENTRAT POMIDOROWY", count: 0 },
  { item: "CUKIER PUDER", count: 0 },
  { item: "PROSZEK DO PIECZENIA", count: 0 },
  { item: "CUKIER WANILIOWY", count: 0 },
  { item: "SODA OCZYSZCZONA", count: 0 },
  { item: "KWASEK CYTRYNOWY ", count: 0 },
  { item: "ZELATYNA", count: 0 },
  { item: "DROZDZE SUCHE", count: 0 },
  { item: "BUDYN WANILIOWY", count: 0 },
  { item: "ZUREK", count: 0 },
  { item: "MAGI", count: 0 },
  { item: "OCET 10%", count: 0 },
  { item: "OCET JABLKOWY", count: 0 },
  { item: "FASOLA JAS ", count: 0 },
  { item: "BULKA TARTA", count: 0 },
  { item: "MAKA TORTOWA", count: 0 },
  { item: "MAKA PSZENNA NA CHLEB", count: 0 },
  { item: "MAKA ZIEMNIACZANA", count: 0 },
  { item: "OSCYPEK", count: 0 },
  { item: "CHRZAN TARTY", count: 0 },
  { item: "MUSZTARDA", count: 0 },
  { item: "PIETRUSZKA KORZEN", count: 0 },
  { item: "SELER KORZEN", count: 0 },
  { item: "BURAKI SWIEZE", count: 0 },
  { item: "TWAROG POLTLUSTY", count: 0 },
  { item: "SMALEC KOSTKA", count: 0 },
  { item: "SMALEC BATON TARCZYNSKI", count: 0 },
  { item: "MARGARYNA KOSTKA", count: 0 },
];

export default polskaHurtownia;
