const vegetables = [
  { item: "ZIEMNIAKI CZERWONE - RED POTATOES", count: 0 },
  { item: "CEBULA BIALA - WHITE ONNION", count: 0 },
  { item: "KAPUSTA BIALA - WHITE CABBAGE", count: 0 },
  { item: "KAPUSTA CZERWONA - RED CABBAGE", count: 0 },
  { item: "KAPUSTA STORZKOWA - POINTED CABBAGE", count: 0 },
  { item: "MARCHEW - CARROTS", count: 0 },
  { item: "MLODA MARCHEWKA - NEW CARROTS", count: 0 },
  { item: "PAPRYKA MIX - MIX PEPPERS", count: 0 },
  { item: "PIECZARKI - MUSHROOMS", count: 0 },
  { item: "PIETRUSZKA DEKORACYJNA - PARSLEY", count: 0 },
  { item: "OGOREK SWIEZY - CUCUMBER", count: 0 },
  { item: "CYTRYNY - LEMON", count: 0 },
  { item: "LIMONKI - LIME", count: 0 },
  { item: "JABLKA - APPLE", count: 0 },
  { item: "POMIDORY DUZE - LARGE TOMATOES", count: 0 },
  { item: "POMIDORKI KOKTAJLOWE - COCTAIL TOMATOES", count: 0 },
  { item: "KALAFIOR DUZY - CAULIFLOWER", count: 0 },
  { item: "SALATA MIX - MIX SALAD", count: 0 },
  { item: "RUKOLA - ROCKET SALAD", count: 0 },
  { item: "POR - LEEK", count: 0 },
  { item: "MIETA - MINT", count: 0 },
  { item: "KOPER - DILL ", count: 0 },
  { item: "SZCZYPIOR GRUBY - SPRING ONIONS", count: 0 },
  { item: "ROZMARYN - RESEMARY", count: 0 },
  { item: "TYMIANEK - THYME", count: 0 },
  { item: "MASLO ZWYKLE - BUTTER ", count: 0 },
  { item: "ZURAWINA -CRAMBERY SAUCE", count: 0 },
  { item: "JAJKA - EGG", count: 0 },
  { item: "MLEKO - MILK", count: 0 },
  { item: "KWASNA SMIETANA - SOUR CREAM", count: 0 },
  { item: "SMIETANA 36% - WEEPING CREAM", count: 0 },
];

export default vegetables;
